services:
  sdc:
    image: bedasoftware/fhir-sdc:2.0.0a2
    depends_on:
      devbox:
        condition: service_healthy
    env_file:
      - ./env/sdc
  devbox:
    image: healthsamurai/aidboxone:stable
    depends_on:
      devbox-db:
        condition: service_healthy
      build-seeds:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 50
    ports:
      - 8080:8080
    env_file:
      - ./env/aidbox
    environment:
      - AIDBOX_LICENSE
    volumes:
      - ./resources/init-bundles:/resources/init-bundles
  devbox-db:
    image: "postgres:18"
    env_file:
      - ./env/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  build-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - export
      - --output
      - /app/init-bundles/initBundle.json
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
    volumes:
      - ./resources/seeds:/app/resources:ro
      - ./resources/init-bundles:/app/init-bundles
    env_file:
      - ./env/build-seeds
  watch-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - watch
      - --external-fhir-server-url
      - http://root:secret@devbox:8080
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
    volumes:
      - ./resources/seeds:/app/resources:ro
    env_file:
      - ./env/build-seeds
  fhir-converters-app:
    image: bedasoftware/aidbox-fhir-converter:main
    depends_on:
      devbox:
        condition: service_healthy
    env_file:
      - ./env/fhir-converters-app
  questionnaire-fce-fhir-converter:
    image: bedasoftware/questionnaire-fce-fhir-converter:latest
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 50
